// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTG4HvqZ74v8hWCS9jPR4gIgkIWHfBWqI',
    appId: '1:651983842055:web:2ca6cd2b8bc7621fa2b3a2',
    messagingSenderId: '651983842055',
    projectId: 'exercise-387ec',
    authDomain: 'exercise-387ec.firebaseapp.com',
    databaseURL: 'https://exercise-387ec-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'exercise-387ec.appspot.com',
    measurementId: 'G-T7EGYZE1BV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE7umvWU3_G0we-JIA8Gt2nHr6Nz8MaeQ',
    appId: '1:651983842055:android:a6ffeedeca0c7555a2b3a2',
    messagingSenderId: '651983842055',
    projectId: 'exercise-387ec',
    databaseURL: 'https://exercise-387ec-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'exercise-387ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9rsglzfM_hFMnT71ejgMYMxku7fh7FWM',
    appId: '1:651983842055:ios:c27714b6f0a211a3a2b3a2',
    messagingSenderId: '651983842055',
    projectId: 'exercise-387ec',
    databaseURL: 'https://exercise-387ec-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'exercise-387ec.appspot.com',
    iosClientId: '651983842055-6u24orvglnrksvkqftcfoqn4r88i18kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.exercise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9rsglzfM_hFMnT71ejgMYMxku7fh7FWM',
    appId: '1:651983842055:ios:c27714b6f0a211a3a2b3a2',
    messagingSenderId: '651983842055',
    projectId: 'exercise-387ec',
    databaseURL: 'https://exercise-387ec-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'exercise-387ec.appspot.com',
    iosClientId: '651983842055-6u24orvglnrksvkqftcfoqn4r88i18kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.exercise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTG4HvqZ74v8hWCS9jPR4gIgkIWHfBWqI',
    appId: '1:651983842055:web:43b2c2bf6f00fd77a2b3a2',
    messagingSenderId: '651983842055',
    projectId: 'exercise-387ec',
    authDomain: 'exercise-387ec.firebaseapp.com',
    databaseURL: 'https://exercise-387ec-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'exercise-387ec.appspot.com',
    measurementId: 'G-8WQJ4Q4P1G',
  );

}